// Mapa de códigos del CSV a nombres completos de selecciones
export const TEAM_NAMES: Record<string, string> = {
  'MEX': 'México',
  'SUD': 'Sudáfrica',
  'COR': 'Corea del Sur',
  'CZE': 'Chequia',
  'USA': 'Estados Unidos',
  'CAN': 'Canadá',
  'ARG': 'Argentina',
  'BRA': 'Brasil',
  'ESP': 'España',
  'FRA': 'Francia',
  'ALE': 'Alemania',
  'ING': 'Inglaterra',
  'POR': 'Portugal',
  'BEL': 'Bélgica',
  'CRO': 'Croacia',
  'URU': 'Uruguay',
  'COL': 'Colombia',
  'JAP': 'Japón',
  'MAR': 'Marruecos',
  'SEN': 'Senegal',
  'AUS': 'Australia',
  'SUI': 'Suiza',
  'AUT': 'Austria',
  'TUR': 'Turquía',
  'NOR': 'Noruega',
  'SUE': 'Suecia',
  'SWE': 'Suecia',
  'ECU': 'Ecuador',
  'PAR': 'Paraguay',
  'PAN': 'Panamá',
  'QAT': 'Qatar',
  'IRA': 'Irán',
  'IRQ': 'Irak',
  'GHA': 'Ghana',
  'TUN': 'Túnez',
  'EGI': 'Egipto',
  'NZ': 'Nueva Zelanda',
  'HAI': 'Haití',
  'CUR': 'Curazao',
  'JOR': 'Jordania',
  'UZB': 'Uzbekistán',
  'ESC': 'Escocia',
  'ARA': 'Arabia Saudí',
  'ARB': 'Arabia Saudí',
  'PBJ': 'Países Bajos',
  'B&H': 'Bosnia y Herzegovina',
  'CAB': 'Cabo Verde',
  'CMF': 'Camerún',
  'RDC': 'RD Congo',
}

export function getTeamName(code: string): string {
  return TEAM_NAMES[code] || code
}
